today = input("Ведите дату: ")
todayTask = input("Введите задачу: ")
tomorrow = input("Ведите дату: ")
tomorrowTask = input("Введите задачу: ")
afterTomorrow = input("Введите дату: ")
afterTomorrowTask = input("Введите задачу: ")
print(today, todayTask)
print(tomorrow, tomorrowTask)
print(afterTomorrow, afterTomorrowTask)